name: Test - Observability

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 4"

permissions:
  id-token: write
  contents: read

jobs:
  test-chaos:
    uses: ./.github/workflows/module-test.yaml
    with:
      module: observability/high-availability
    secrets: inherit